import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h3 className="text-blue-500">Haiku App</h3>
        </header>
        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}
